### ISSUE TITLE
For beginners: How to run?

### ISSUE THREAD

**Issue by m-mohr** [openEOPlatform/SRR1_notebooks#1]
I'm trying to run the notebooks and I'm a beginner in Python:

Just running a single notebooks errors and shows that I need to load the eo_utils. 
After I've added them, it complains about missing packages. How to load them?
There's an environment.yaml, but how to load it? 

I think the readme of this readme should give a step-by-step guide how to run the notebooks.

**Comment by clausmichele** [comment]
Let me know if you think that the current instructions are clear enough now

**Comment by m-mohr** [comment]
Thanks.
